"""empty message

Revision ID: 328ee867ab17
Revises: 
Create Date: 2024-12-17 02:00:39.952131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '328ee867ab17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testers', schema=None) as batch_op:
        batch_op.alter_column('project_name_id',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=postgresql.ARRAY(sa.String(length=100), as_tuple=ForeignKey('project_name.id')),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testers', schema=None) as batch_op:
        batch_op.alter_column('project_name_id',
               existing_type=postgresql.ARRAY(sa.String(length=100), as_tuple=ForeignKey('project_name.id')),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    # ### end Alembic commands ###
